package com.aihwaong.minicm.mapper;

import com.aihwaong.minicm.model.HouseholdAccount;

public interface HouseholdAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_household_account
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_household_account
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    int insert(HouseholdAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_household_account
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    int insertSelective(HouseholdAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_household_account
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    HouseholdAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_household_account
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    int updateByPrimaryKeySelective(HouseholdAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_household_account
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    int updateByPrimaryKey(HouseholdAccount record);
}