package com.aihwaong.minicm.model;

import java.util.Date;

public class Chamber {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_chamber.id
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_chamber.chamber_name
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    private String chamberName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_chamber.create_time
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_chamber.update_time
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_chamber.status
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_chamber.is_delete
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    private String isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_chamber.id
     *
     * @return the value of cm_chamber.id
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_chamber.id
     *
     * @param id the value for cm_chamber.id
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_chamber.chamber_name
     *
     * @return the value of cm_chamber.chamber_name
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public String getChamberName() {
        return chamberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_chamber.chamber_name
     *
     * @param chamberName the value for cm_chamber.chamber_name
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setChamberName(String chamberName) {
        this.chamberName = chamberName == null ? null : chamberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_chamber.create_time
     *
     * @return the value of cm_chamber.create_time
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_chamber.create_time
     *
     * @param createTime the value for cm_chamber.create_time
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_chamber.update_time
     *
     * @return the value of cm_chamber.update_time
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_chamber.update_time
     *
     * @param updateTime the value for cm_chamber.update_time
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_chamber.status
     *
     * @return the value of cm_chamber.status
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_chamber.status
     *
     * @param status the value for cm_chamber.status
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_chamber.is_delete
     *
     * @return the value of cm_chamber.is_delete
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_chamber.is_delete
     *
     * @param isDelete the value for cm_chamber.is_delete
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }
}