package com.aihwaong.minicm.model;

import java.util.Date;

public class StoriedHouse {

    private Integer id;

    private Integer ridgepole;

    private Integer unit;

    private String storey;

    private String roomNumber;

    private Integer chamber;

    private Integer hall;

    private String floorSpace;

    private String housePrice;

    private String ridgepoleName;

    private String unitName;

    private String chamberName;

    private String hallName;

    private String houseType;

    private Date createTime;

    private Date updateTime;

    private Date checkInTime;

    private Byte status;

    private String isDelete;

    public Date getCheckInTime() {
        return checkInTime;
    }

    public void setCheckInTime(Date checkInTime) {
        this.checkInTime = checkInTime;
    }

    public String getHouseType() {
        return houseType;
    }

    public void setHouseType(String houseType) {
        this.houseType = houseType;
    }

    public String getRidgepoleName() {
        return ridgepoleName;
    }

    public void setRidgepoleName(String ridgepoleName) {
        this.ridgepoleName = ridgepoleName;
    }

    public String getUnitName() {
        return unitName;
    }

    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    public String getChamberName() {
        return chamberName;
    }

    public void setChamberName(String chamberName) {
        this.chamberName = chamberName;
    }

    public String getHallName() {
        return hallName;
    }

    public void setHallName(String hallName) {
        this.hallName = hallName;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_storied_house.id
     *
     * @return the value of cm_storied_house.id
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_storied_house.id
     *
     * @param id the value for cm_storied_house.id
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_storied_house.ridgepole
     *
     * @return the value of cm_storied_house.ridgepole
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public Integer getRidgepole() {
        return ridgepole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_storied_house.ridgepole
     *
     * @param ridgepole the value for cm_storied_house.ridgepole
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setRidgepole(Integer ridgepole) {
        this.ridgepole = ridgepole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_storied_house.unit
     *
     * @return the value of cm_storied_house.unit
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public Integer getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_storied_house.unit
     *
     * @param unit the value for cm_storied_house.unit
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setUnit(Integer unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_storied_house.storey
     *
     * @return the value of cm_storied_house.storey
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public String getStorey() {
        return storey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_storied_house.storey
     *
     * @param storey the value for cm_storied_house.storey
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setStorey(String storey) {
        this.storey = storey == null ? null : storey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_storied_house.room_number
     *
     * @return the value of cm_storied_house.room_number
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public String getRoomNumber() {
        return roomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_storied_house.room_number
     *
     * @param roomNumber the value for cm_storied_house.room_number
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber == null ? null : roomNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_storied_house.chamber
     *
     * @return the value of cm_storied_house.chamber
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public Integer getChamber() {
        return chamber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_storied_house.chamber
     *
     * @param chamber the value for cm_storied_house.chamber
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setChamber(Integer chamber) {
        this.chamber = chamber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_storied_house.hall
     *
     * @return the value of cm_storied_house.hall
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public Integer getHall() {
        return hall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_storied_house.hall
     *
     * @param hall the value for cm_storied_house.hall
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setHall(Integer hall) {
        this.hall = hall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_storied_house.floor_space
     *
     * @return the value of cm_storied_house.floor_space
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public String getFloorSpace() {
        return floorSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_storied_house.floor_space
     *
     * @param floorSpace the value for cm_storied_house.floor_space
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setFloorSpace(String floorSpace) {
        this.floorSpace = floorSpace == null ? null : floorSpace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_storied_house.house_price
     *
     * @return the value of cm_storied_house.house_price
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public String getHousePrice() {
        return housePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_storied_house.house_price
     *
     * @param housePrice the value for cm_storied_house.house_price
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setHousePrice(String housePrice) {
        this.housePrice = housePrice == null ? null : housePrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_storied_house.create_time
     *
     * @return the value of cm_storied_house.create_time
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_storied_house.create_time
     *
     * @param createTime the value for cm_storied_house.create_time
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_storied_house.update_time
     *
     * @return the value of cm_storied_house.update_time
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_storied_house.update_time
     *
     * @param updateTime the value for cm_storied_house.update_time
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_storied_house.status
     *
     * @return the value of cm_storied_house.status
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_storied_house.status
     *
     * @param status the value for cm_storied_house.status
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_storied_house.is_delete
     *
     * @return the value of cm_storied_house.is_delete
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_storied_house.is_delete
     *
     * @param isDelete the value for cm_storied_house.is_delete
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }
}