package com.aihwaong.minicm.model;

import java.util.Date;

public class VehicleRegistration {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vehicle_registration.id
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    private Integer id;

    public Integer getHouseholdId() {
        return householdId;
    }

    public void setHouseholdId(Integer householdId) {
        this.householdId = householdId;
    }

    private Integer householdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vehicle_registration.brand
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vehicle_registration.type
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vehicle_registration.plate_number
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    private String plateNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vehicle_registration.contacts
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    private String contacts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vehicle_registration.telephone
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vehicle_registration.external
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    private String external;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vehicle_registration.create_time
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vehicle_registration.update_time
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vehicle_registration.status
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_vehicle_registration.is_delete
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    private String isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vehicle_registration.id
     *
     * @return the value of cm_vehicle_registration.id
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vehicle_registration.id
     *
     * @param id the value for cm_vehicle_registration.id
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vehicle_registration.brand
     *
     * @return the value of cm_vehicle_registration.brand
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vehicle_registration.brand
     *
     * @param brand the value for cm_vehicle_registration.brand
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vehicle_registration.type
     *
     * @return the value of cm_vehicle_registration.type
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vehicle_registration.type
     *
     * @param type the value for cm_vehicle_registration.type
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vehicle_registration.plate_number
     *
     * @return the value of cm_vehicle_registration.plate_number
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vehicle_registration.plate_number
     *
     * @param plateNumber the value for cm_vehicle_registration.plate_number
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber == null ? null : plateNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vehicle_registration.contacts
     *
     * @return the value of cm_vehicle_registration.contacts
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vehicle_registration.contacts
     *
     * @param contacts the value for cm_vehicle_registration.contacts
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vehicle_registration.telephone
     *
     * @return the value of cm_vehicle_registration.telephone
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vehicle_registration.telephone
     *
     * @param telephone the value for cm_vehicle_registration.telephone
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vehicle_registration.external
     *
     * @return the value of cm_vehicle_registration.external
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public String getExternal() {
        return external;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vehicle_registration.external
     *
     * @param external the value for cm_vehicle_registration.external
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setExternal(String external) {
        this.external = external == null ? null : external.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vehicle_registration.create_time
     *
     * @return the value of cm_vehicle_registration.create_time
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vehicle_registration.create_time
     *
     * @param createTime the value for cm_vehicle_registration.create_time
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vehicle_registration.update_time
     *
     * @return the value of cm_vehicle_registration.update_time
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vehicle_registration.update_time
     *
     * @param updateTime the value for cm_vehicle_registration.update_time
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vehicle_registration.status
     *
     * @return the value of cm_vehicle_registration.status
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vehicle_registration.status
     *
     * @param status the value for cm_vehicle_registration.status
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_vehicle_registration.is_delete
     *
     * @return the value of cm_vehicle_registration.is_delete
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_vehicle_registration.is_delete
     *
     * @param isDelete the value for cm_vehicle_registration.is_delete
     *
     * @mbg.generated Wed Jun 17 17:11:04 CST 2020
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }
}